server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /canasta {
    return 301 /canasta/;
  }

  location /canasta/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /canasta/index.html;
  }
}
